stages:
- name: Run tests
  steps:
  - runScriptConfig:
      image: maven:3-openjdk-8
      shellScript: mvn test -pl ${PROJECT} -Dkarate.env=${ENVIRONMENT} && ls
    envFrom:
    - sourceName: integration-tests
      sourceKey: project
      targetKey: PROJECT
    - sourceName: integration-tests
      sourceKey: environment
      targetKey: ENVIRONMENT
    cpuRequest: 100m
    memoryRequest: 500Mi
    memoryLimit: 1Gi
  - runScriptConfig:
      image: amazon/aws-cli
      shellScript: ls
- name: S3 upload
  steps:
  - runScriptConfig:
      image: amazon/aws-cli
      shellScript: ls
timeout: 60
notification: {}
